# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('story_line', models.TextField()),
                ('poster_image_url', models.CharField(max_length=255)),
                ('trailer_youtube_url', models.CharField(max_length=255)),
            ],
        ),
    ]
